services:
  api:
    image: ghcr.io/jeff1728/demo-cicd-api:latest
    container_name: demo-cicd-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GIT_SHA=loc
